### ISSUE TITLE
[Feature Request] Some Suggestions

### ISSUE THREAD

**Issue by axl303** [SmileYzn/MatchBot#79]
Some suggestions / ideas. You may like/dislike something. You can add whatever you like from the suggestions :)

1. Make the main configs in one big file called Matchbot.cfg with configs list like GetPrivateProfileString API Windows (Used it MuOnline hehe :))

Example:

[Admins]
...

[Maps]
....

2. A Stats/Money Player save after he leaves the match (Up to 3 rounds? I think it's ok) - Like CS:GO

3. A bot control, something like: "press E to control bot" - Like CS:GO

4. A DeathMsg with bomb message when someone is killed by bomb or by bomb planter like CS:GO. Saw it on your PugMod AMXX Version :) I liked it.

5. ICC (Intel) Compiler - Rehlds, Regamedll, Metamod-r (All RE) are using it. From my tests on Intel CPU gcc and icc made a difference in server fps drops (Intel compiler won).

**Comment by SmileYzn** [comment]
1. matchbot.cfg is a console variables file. It is compatible with server itsef.
2. INI files is a kick in the ass at linux systems, it is designed only to work native on windows. 
3. This is out of scope of matchbot, you can use 3rd party plugins to do that
4. I did not remember correctly from that, but is also other thing that can be done using plugins.
5. ICC was dropped support from linux kernel probably ReHLDS and ReGameDLL_CS will do too if you se latest action builds. That means is not a good choice, and is not totally really true that icc performs better than gcc compiler!

I will start to do a cleanup in MatchBOT and maintain on it only things that is related to match.

**Comment by axl303** [comment]
> 5. ICC was dropped support from linux kernel probably ReHLDS and ReGameDLL_CS will do too if you se latest action builds. That means is not a good choice, and is not totally really true that icc performs better than gcc compiler!
 
Linux 6.3 Drops Support For The Intel ICC Compiler
Oooh, sorry My bad.
From the tests I did on old CPU like I7-6700k(Launch Date Q3'15) it showed stable fps on icc. But it's not a big deal.

Do we have any chance to get the "Stats/Money Player save after he leaves the match (Up to 3 rounds?)" in the MatchBot/RePugMod available?

**Comment by SmileYzn** [comment]
> > 5. ICC was dropped support from linux kernel probably ReHLDS and ReGameDLL_CS will do too if you se latest action builds. That means is not a good choice, and is not totally really true that icc performs better than gcc compiler!
> 
> Linux 6.3 Drops Support For The Intel ICC Compiler Oooh, sorry My bad. From the tests I did on old CPU like I7-6700k(Launch Date Q3'15) it showed stable fps on icc. But it's not a big deal.
> 
> Do we have any chance to get the "Stats/Money Player save after he leaves the match (Up to 3 rounds?)" in the MatchBot/RePugMod available?

This can be added in future!

**Comment by F4ntik** [comment]
(I'm sorry I'm using a translator):

Wouldn't it be better to roll back the round to the beginning and wait for the player to reconnect. 
This feature can be implemented:
1) A vote appears: "Waiting for the player: yes/no"
2) If n-seconds have not passed since the start of the round, then the round is rolled back and the waiting time (n-seconds) is set to connect the player.
3) Otherwise, the player's expectation is turned on in the next round. 
4) The player connects with saving the "Stats / money of the player" and the match continues after the waiting time, or / ready messages of the players.
5) If the player's waiting vote failed or the waiting time has expired, then the match continues -> "Statistics/Money saved by the player after he leaves the match (up to N rounds).  The waiting time can also be extended by n-seconds, a maximum of n-times. 
The admin can set an infinite waiting time for the player. Or roll back the match for a certain round.

**Comment by F4ntik** [comment]
And if it's not a random player? And the player is from the team, and it is desirable to wait for him, especially if the vote "wait for the player or not to wait" appears.
Or there is some kind of mini-tournament among pensioners :)

**Comment by SmileYzn** [comment]
Match pause when player is lacking in any team on round restart already implemented.
An 'mini-tournament' player should reconnect in 60 seconds.
